name = "rurki"
uuid = "1cf06df4-d55a-4eb3-8b99-a5a7aace01d9"
authors = ["Jakub Karbowski <carbon@student.agh.edu.pl>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
